"""La cadena de migraciones corre desde base vacia y los modelos no tienen deriva.

Estos tests reconstruyen el schema, asi que corren aislados del resto de la suite: piden
`fixtures` al final para dejar los datos sembrados de nuevo.
"""

from __future__ import annotations

from pathlib import Path

import pytest
from alembic.command import check, downgrade, upgrade
from alembic.config import Config
from alembic.util.exc import AutogenerateDiffsDetected
from sqlalchemy import Engine, text

from tests.conftest import Fixtures, seed_fixture_data

pytestmark = pytest.mark.integration

BACKEND_ROOT = Path(__file__).resolve().parents[2]

EXPECTED_REVISIONS = [
    "0001_baseline",
    "0002_session_context",
    "0003_tenant",
    "0004_role_permission_catalog",
    "0005_principal",
    "0006_tenant_membership",
    "0007_membership_policies",
]


@pytest.fixture
def alembic_config() -> Config:
    config = Config(str(BACKEND_ROOT / "alembic.ini"))
    config.set_main_option("script_location", str(BACKEND_ROOT / "migrations"))
    return config


def test_revision_ids_fit_the_version_column() -> None:
    """`alembic_version.version_num` es varchar(32); un id mas largo rompe el upgrade."""
    for revision in EXPECTED_REVISIONS:
        assert len(revision) <= 32, f"{revision} tiene {len(revision)} caracteres"


def test_upgrade_from_empty_and_back(
    alembic_config: Config,
    owner_engine: Engine,
    seed_engine: Engine,
    fixtures: Fixtures,
) -> None:
    """Reconstruye el schema y vuelve a sembrar, sin depender del orden de ejecucion."""
    downgrade(alembic_config, "base")

    with owner_engine.connect() as connection:
        remaining = (
            connection.execute(
                text(
                    "SELECT c.relname FROM pg_class c "
                    "JOIN pg_namespace n ON n.oid = c.relnamespace "
                    "WHERE n.nspname = 'public' AND c.relkind = 'r' "
                    "AND c.relname <> 'alembic_version'"
                )
            )
            .scalars()
            .all()
        )
    assert remaining == [], f"downgrade base dejo tablas: {remaining}"

    upgrade(alembic_config, "head")

    with owner_engine.connect() as connection:
        current = connection.execute(
            text("SELECT version_num FROM alembic_version")
        ).scalar_one()
    assert current == EXPECTED_REVISIONS[-1]

    # El schema quedo vacio; se repuebla explicitamente para el resto de la suite.
    seed_fixture_data(seed_engine, fixtures)


def test_models_match_the_migrated_schema(alembic_config: Config) -> None:
    """`alembic check` falla si un modelo y su migracion se separaron."""
    try:
        check(alembic_config)
    except AutogenerateDiffsDetected as exc:  # pragma: no cover - solo si hay deriva
        pytest.fail(f"Los modelos no coinciden con el schema migrado: {exc}")
